version: '3'

services:
# DATABASE
  mongo:
    image: mongo:4.0-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DBUSER
      - MONGO_INITDB_ROOT_PASSWORD=$DBPASS
    ports:
      - "3003:27017"
    expose:
      - "27017"
    volumes:
      - uno-data:/data/db
    restart: always

# SERVER
  api:
    build:
      context: server
    environment:
      - PORT=3001
      - DBHOST=mongo
      - DBPORT=27017
      - DBUSER=$DBUSER
      - DBPASS=$DBPASS
      - DEBUG=$DEBUG
      - DAY_LOG=$DAY_LOG
      - SECRET_REQUEST=$SECRET_REQUEST
      - FACEBOOK_APP_ID=$FACEBOOK_APP_ID
    expose:
      - "3001"
    networks:
      - nginx-network
    depends_on:
      - mongo
    restart: always

# CLIENT
  client:
    build:
      context: client
      args:
        - HOST_SERVER=$HOST_SERVER
        - SECRET_REQUEST=$SECRET_REQUEST
    networks:
      - nginx-network
    depends_on:
      - api
    restart: always

# PROXY
  proxy:
    build:
      context: proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-network
    depends_on:
      - client

volumes:
  uno-data:

networks:
  nginx-network:
